apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dnsrbl-exporter
  namespace: monitoring
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      main:
        enabled: true
        containers:
          main:
            image:
              repository: runningman84/dnsrbl-exporter
              tag: latest
            env:
              TZ: "Europe/Berlin"
            probes:
              liveness:
                enabled: true
            securityContext:
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 65534

    service:
      main:
        enabled: true
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 8000

    serviceMonitor:
      main:
        enabled: true
        serviceName: dnsrbl-exporter
        endpoints:
          - port: http
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
